output_path=/local/zemel/gzg2104/_emnist_models/06_23_24/common_encoder/beta5_eps_1e-4_blr_1e-3_400total_decay_0_1
python main_pretrain.py \
    --dataset_name emnist \
    --batch_size 384 \
    --blr 1e-3 \
    --accum_iter 1 \
    --output_dir $output_path \
    --log_dir $output_path \
    --model mae_vit_base_patch16 \
    --warmup_epochs 40 \
    --epochs 400 \
    --log_freq 40 \
    --vae \
    --kld_beta 5 \
    --invisible_lr_scale 0.1 \
    --mask_ratio 0.75 \
    --partial_vae \
    --dropout_ratio 0 \
    --eps 1e-4 \
    --weight_decay 0.1 \
    --mixed_precision \
    --same_encoder \
    --block_mask_prob 0 \
    --wandb_project emnist_pretrain